from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('change-password/', views.change_password, name='change_password'),
    # Admin panel
    path('panel/students/', views.admin_students, name='admin_students'),
    path('panel/students/add/', views.admin_add_student, name='admin_add_student'),
    path('panel/parents/', views.admin_parents, name='admin_parents'),
    path('panel/parents/add/', views.admin_add_parent, name='admin_add_parent'),
    path('panel/results/', views.admin_results, name='admin_results'),
    path('panel/results/add/', views.admin_add_result, name='admin_add_result'),
    path('panel/news/', views.admin_news, name='admin_news'),
    path('panel/news/add/', views.admin_add_news, name='admin_add_news'),
    path('panel/events/', views.admin_events, name='admin_events'),
    path('panel/events/add/', views.admin_add_event, name='admin_add_event'),
    path('panel/applications/', views.admin_applications, name='admin_applications'),
    path('panel/applications/<int:pk>/<str:action>/', views.admin_application_action, name='admin_application_action'),
    path('panel/messages/', views.admin_messages, name='admin_messages'),
    path('panel/messages/<int:pk>/read/', views.admin_message_read, name='admin_message_read'),
    path('panel/staff/', views.admin_staff, name='admin_staff'),
    path('panel/staff/add/', views.admin_add_staff, name='admin_add_staff'),
    path('panel/gallery/', views.admin_gallery, name='admin_gallery'),
    path('panel/gallery/add/', views.admin_add_album, name='admin_add_album'),
    path('panel/classes/', views.admin_classes, name='admin_classes'),
    path('panel/classes/add/', views.admin_add_class, name='admin_add_class'),
    path('panel/subjects/', views.admin_subjects, name='admin_subjects'),
    path('panel/subjects/add/', views.admin_add_subject, name='admin_add_subject'),
    path('panel/enroll/', views.admin_enroll_student, name='admin_enroll_student'),
    path('panel/timetable/', views.admin_timetable, name='admin_timetable'),
    path('panel/timetable/add/', views.admin_add_timetable, name='admin_add_timetable'),
    path('panel/fees/', views.admin_fees, name='admin_fees'),
    path('panel/fees/add/', views.admin_add_fee, name='admin_add_fee'),
    path('panel/delete/<str:model>/<int:pk>/', views.admin_delete, name='admin_delete'),
]
