# Generated by Django 4.2.30 on 2026-05-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography'),
        ),
        migrations.AddField(
            model_name='staff',
            name='experience',
            field=models.CharField(blank=True, help_text='e.g. 10 years', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. B.Sc Physics, M.Ed', max_length=200),
        ),
    ]
