# Generated by Django 5.2.17 on 2026-09-27 19:45 (manually edited)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Step 1: Add must_change_password field only
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='If True, user will be required to change password on next login.'),
        ),
    ]
